/**
 * brain-db.js — Brain DB provisioning helpers.
 *
 * Called by `agentbootup brain restore` as Phase 4 (memory sync).
 * Provisions a libSQL embedded-replica brain.db for the target project.
 *
 * What this does:
 *   - Calls /v1/brain-db/provision on agentbootup server to get DB URL + auth token
 *   - Writes .brain/db.ts (libSQL client init + sync helpers) to target project
 *   - Copies brain-schema.sql to brain/brain-schema.sql (FR-07) and .brain/brain-schema.sql (runtime mirror)
 *   - Appends BRAIN_DB_URL + BRAIN_DB_TOKEN to target project .env
 *   - Allocates inbox port (8767–8867) and generates HMAC webhook secret (AB-1, AB-2)
 *   - Appends AGENTBOOTUP_INBOX_PORT + AGENTBOOTUP_INBOX_WEBHOOK_SECRET to .env (AB-4)
 *   - Adds .brain/brain.db to target project .gitignore (idempotent)
 *
 * Sync is handled by the agentbootup-brain-db-<id> agent-process daemon
 * (registered by `agentbootup daemon start`), not by session hooks.
 * The embedded replica's syncInterval:300 keeps data fresh in the background.
 *
 * If BRAIN_DB_URL is not available (server doesn't support it yet),
 * runs in file-only mode: db.ts and schema still written, no remote sync.
 *
 * The generated .brain/db.ts now degrades to local-only mode if the remote
 * sync target is unreachable at startup and exposes syncDb()/verifySyncHealth()
 * so downstream consumers can adopt the same best-effort replica contract.
 */

import fs from 'fs';
import path from 'path';
import { execFileSync } from 'child_process';
import { fileURLToPath } from 'url';
import { apiUrl } from '../auth/validate.js';
import { allocateInboxPort } from './port-registry.js';
import { provisionWebhookSecret } from './webhook-secret.js';
import { setInboxEnabled } from '../config/config.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** PRD-0014 FR-07 — committed path in each brain repo (developer-facing contract). */
export const BRAIN_SCHEMA_REL_COMMITTED = path.join('brain', 'brain-schema.sql');
/** Same bytes as {@link BRAIN_SCHEMA_REL_COMMITTED}; under .brain/ for applySchema / ignored runtime. */
export const BRAIN_SCHEMA_REL_RUNTIME = path.join('.brain', 'brain-schema.sql');

/**
 * Path to use for BRAIN_DB_SCHEMA_PATH: prefer committed `brain/brain-schema.sql`, else legacy `.brain/` copy.
 * @param {string} projectRoot Absolute project root
 * @returns {string | null} null if neither file exists
 */
export function resolveBrainSchemaPathForProject(projectRoot) {
  const committed = path.join(projectRoot, BRAIN_SCHEMA_REL_COMMITTED);
  const runtime = path.join(projectRoot, BRAIN_SCHEMA_REL_RUNTIME);
  if (fs.existsSync(committed)) return committed;
  if (fs.existsSync(runtime)) return runtime;
  return null;
}

/** Path to brain-schema.sql — bundled template first (PRD-0014 FR-07), then optional sibling clone. */
const SCHEMA_SOURCE_PATHS = [
  path.resolve(__dirname, '../../templates/brain/brain-schema.sql'),
  path.resolve(__dirname, '../../../decisive_redux/brain/brain-schema.sql'),
];

const PROVISION_TIMEOUT_MS = 15_000;

// ─────────────────────────────────────────────────────────
// File template written to the target project
// ─────────────────────────────────────────────────────────

const DB_TS_TEMPLATE = `// .brain/db.ts — libSQL embedded-replica client for brain.db
// Auto-generated by agentbootup brain restore. Do not edit manually.
// Re-run \`agentbootup brain restore\` to regenerate.
import { createClient } from '@libsql/client';

const localUrl = 'file:.brain/brain.db';
const syncUrl = process.env.BRAIN_DB_URL || null;
const authToken = process.env.BRAIN_DB_TOKEN || undefined;

const syncConfigured = Boolean(syncUrl && authToken);

export let brainDbMode = syncConfigured ? 'embedded-replica' : 'file-only';

function createLocalClient() {
  if (!syncConfigured) return createClient({ url: localUrl });
  try {
    return createClient({ url: localUrl, syncUrl, authToken, syncInterval: 300 });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.warn(\`[brain-db] remote sync unavailable at startup; continuing with local replica: \${message}\`);
    brainDbMode = 'embedded-replica-offline';
    return createClient({ url: localUrl });
  }
}

export const db = createLocalClient();

function canAttemptRemoteSync() {
  return syncConfigured && brainDbMode !== 'embedded-replica-offline';
}

export async function syncDb(client = db) {
  if (!canAttemptRemoteSync() || typeof client?.sync !== 'function') return;
  await client.sync();
}

export async function verifySyncHealth(client = db) {
  if (!syncConfigured) return true;
  if (brainDbMode === 'embedded-replica-offline') return false;

  const probeKey = \`agentbootup-sync-probe-\${Date.now()}\`;
  const probeValue = 'ok';
  const remoteClient = createClient({ url: syncUrl, authToken });

  try {
    await client.execute({
      sql: 'INSERT INTO schema_meta (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value',
      args: [probeKey, probeValue],
    });
    await syncDb(client);

    const result = await remoteClient.execute({
      sql: 'SELECT value FROM schema_meta WHERE key = ?',
      args: [probeKey],
    });
    const remoteValue = result?.rows?.[0]?.value;
    if (remoteValue !== probeValue) return false;

    await client.execute({ sql: 'DELETE FROM schema_meta WHERE key = ?', args: [probeKey] });
    await syncDb(client);
    return true;
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.warn(\`[brain-db] sync verification failed: \${message}\`);
    return false;
  } finally {
    try {
      await remoteClient.execute({ sql: 'DELETE FROM schema_meta WHERE key = ?', args: [probeKey] });
    } catch {
      // best effort cleanup only
    }
    try {
      await remoteClient.close?.();
    } catch {
      // ignore close failures
    }
  }
}
`;

// ─────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────

/**
 * Read the brain-schema.sql from known source locations.
 * Returns null if not found (schema install skipped — daemon still starts).
 * @returns {string | null}
 */
function readSchema() {
  for (const p of SCHEMA_SOURCE_PATHS) {
    try {
      return fs.readFileSync(p, 'utf-8');
    } catch {
      // try next
    }
  }
  return null;
}

/**
 * Write a file to the target project, creating parent dirs as needed.
 * Skips if the file already exists and force is false.
 * @param {string} dest  Absolute path to destination file.
 * @param {string} content  File content.
 * @param {{ force: boolean, dryRun: boolean, verbose: boolean }} opts
 * @returns {'written' | 'skipped' | 'dry-run'}
 */
function writeFile(dest, content, { force, dryRun, verbose }) {
  const exists = fs.existsSync(dest);
  if (exists && !force) {
    if (verbose) console.log(`  skip (exists) ${path.relative(process.cwd(), dest)}`);
    return 'skipped';
  }
  if (dryRun) {
    if (verbose) console.log(`  [dry-run] ${exists ? 'overwrite' : 'write'} ${path.relative(process.cwd(), dest)}`);
    return 'dry-run';
  }
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, content, 'utf-8');
  if (verbose) console.log(`  write ${path.relative(process.cwd(), dest)}`);
  return 'written';
}

/**
 * Append or update key=value pairs in target .env.
 *
 * Default behaviour (force=false): skip keys that are already set.
 * Force behaviour (force=true): replace existing values in-place so that
 * re-running `brain restore --force` refreshes credentials like BRAIN_DB_TOKEN.
 *
 * @param {string} envPath  Absolute path to .env.
 * @param {Record<string, string>} vars
 * @param {{ dryRun: boolean, verbose: boolean, force?: boolean }} opts
 */
function appendEnvVars(envPath, vars, { dryRun, verbose, force = false }) {
  let existing = '';
  try { existing = fs.readFileSync(envPath, 'utf-8'); } catch { /* new file */ }

  // Build existing key set once before the loop to avoid re-splitting on every
  // iteration and to ensure the check is against the original file, not mutations.
  // No .trim() on key extraction — must match the startsWith(`${key}=`) check
  // below; trimming would find indented keys in the set but fail to match them
  // in the replacement. Standard .env files do not indent keys. Note: keys with
  // trailing spaces before '=' (e.g. 'FOO =bar') are out-of-scope and treated
  // as absent — this is acceptable for provisioner-written .env files.
  const existingKeys = new Set(
    existing.split('\n')
      .filter((l) => l.includes('=') && !l.trim().startsWith('#'))
      .map((l) => l.slice(0, l.indexOf('='))),
  );

  const toAppend = [];   // new keys not yet in .env
  let updated = existing; // will hold in-place replacements when force=true

  for (const [key, value] of Object.entries(vars)) {
    if (existingKeys.has(key)) {
      if (force) {
        // Replace existing value in-place — required for credential refresh.
        // Use string-based line replacement (not RegExp) to avoid metacharacter issues.
        if (verbose) console.log(`  [force] update ${key} in .env`);
        if (!dryRun) {
          updated = updated.split('\n').map((l) => l.startsWith(`${key}=`) ? `${key}=${value}` : l).join('\n');
        } else if (verbose) {
          console.log(`  [dry-run] would update ${key} in .env`);
        }
      } else {
        if (verbose) console.log(`  skip (already set) ${key} in .env`);
      }
      continue;
    }
    toAppend.push(`${key}=${value}`);
  }

  if (dryRun) {
    if (verbose) {
      for (const l of toAppend) console.log(`  [dry-run] append .env: ${l.split('=')[0]}=<value>`);
    }
    return;
  }

  // Write back updated content (in-place replacements).
  if (updated !== existing) {
    fs.writeFileSync(envPath, updated, 'utf-8');
  }

  // Append new keys.
  if (toAppend.length > 0) {
    const suffix = (updated.endsWith('\n') || updated === '' ? '' : '\n') + toAppend.join('\n') + '\n';
    fs.appendFileSync(envPath, suffix, 'utf-8');
    if (verbose) {
      for (const l of toAppend) console.log(`  append .env: ${l.split('=')[0]}=<redacted>`);
    }
  }
}

/**
 * Detect the package manager used in a target directory.
 * Returns 'bun' | 'yarn' | 'pnpm' | 'npm' | null (no package.json found).
 * @param {string} targetDir
 * @returns {'bun' | 'yarn' | 'pnpm' | 'npm' | null}
 */
export function detectPackageManager(targetDir) {
  if (!fs.existsSync(path.join(targetDir, 'package.json'))) return null; // nosemgrep
  // Bun 1.1+ uses the text lockfile `bun.lock`; older Bun installations use
  // `bun.lockb`. Either is authoritative evidence that `bun add` is the
  // supported installer for the restored project.
  if (fs.existsSync(path.join(targetDir, 'bun.lockb')) || fs.existsSync(path.join(targetDir, 'bun.lock'))) return 'bun'; // nosemgrep
  if (fs.existsSync(path.join(targetDir, 'yarn.lock')))        return 'yarn'; // nosemgrep
  if (fs.existsSync(path.join(targetDir, 'pnpm-lock.yaml')))   return 'pnpm'; // nosemgrep
  return 'npm';
}

/**
 * Install @libsql/client in a target project using its detected package manager.
 * No-op if already present in dependencies or no package.json found.
 * @param {string} targetDir
 * @param {{ dryRun: boolean, verbose: boolean }} opts
 */
export function installLibsqlClient(targetDir, { dryRun, verbose }) {
  const pm = detectPackageManager(targetDir);
  if (!pm) {
    if (verbose) console.log('  [brain-db] No package.json found — skipping @libsql/client install.');
    return;
  }

  // Check if already installed.
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(targetDir, 'package.json'), 'utf-8')); // nosemgrep
    const deps = { ...pkg.dependencies, ...pkg.devDependencies };
    if (deps['@libsql/client']) {
      if (verbose) console.log('  [brain-db] @libsql/client already in package.json — skipping install.');
      return;
    }
  } catch {
    // Malformed package.json — skip install, don't break provisioning.
    if (verbose) console.log('  [brain-db] Could not parse package.json — skipping @libsql/client install.');
    return;
  }

  // Use execFileSync with explicit args array (not a shell string) to prevent
  // command injection if targetDir contains shell metacharacters.
  const pmConfigs = {
    bun:  { bin: 'bun',  args: ['add', '@libsql/client', '--cwd', targetDir] },
    yarn: { bin: 'yarn', args: ['add', '@libsql/client', '--cwd', targetDir] },
    pnpm: { bin: 'pnpm', args: ['add', '@libsql/client', '--dir', targetDir] },
    npm:  { bin: 'npm',  args: ['install', '@libsql/client', '--prefix', targetDir] },
  };
  const { bin, args } = pmConfigs[pm];

  if (dryRun) {
    if (verbose) console.log(`  [dry-run] install @libsql/client via ${pm}: ${bin} ${args.join(' ')}`);
    return;
  }

  if (verbose) console.log(`  [brain-db] Installing @libsql/client via ${pm}…`);
  try {
    execFileSync(bin, args, { stdio: verbose ? 'inherit' : 'pipe' });
    if (verbose) console.log('  [brain-db] @libsql/client installed.');
  } catch (err) {
    // Non-fatal — db.ts is still written; user can install manually.
    console.warn(`  [brain-db] @libsql/client install failed (${pm}): ${err.message}. Install manually: ${bin} ${args.join(' ')}`);
  }
}

/**
 * Append a gitignore entry to target .gitignore if not already present.
 * @param {string} gitignorePath  Absolute path to .gitignore.
 * @param {string} entry          Line to add (e.g. '.brain/brain.db').
 * @param {{ dryRun: boolean, verbose: boolean }} opts
 */
function appendGitignoreEntry(gitignorePath, entry, { dryRun, verbose }) {
  let existing = '';
  try { existing = fs.readFileSync(gitignorePath, 'utf-8'); } catch { /* new file */ }

  // Match exact line (with or without trailing whitespace).
  const alreadyPresent = existing.split('\n').some((l) => l.trim() === entry);
  if (alreadyPresent) {
    if (verbose) console.log(`  skip (already present) .gitignore: ${entry}`);
    return;
  }

  if (dryRun) {
    if (verbose) console.log(`  [dry-run] append .gitignore: ${entry}`);
    return;
  }

  const toAppend = (existing.endsWith('\n') || existing === '' ? '' : '\n') + entry + '\n';
  fs.appendFileSync(gitignorePath, toAppend, 'utf-8');
  if (verbose) console.log(`  append .gitignore: ${entry}`);
}

// ─────────────────────────────────────────────────────────
// Main export
// ─────────────────────────────────────────────────────────

/**
 * Provision brain.db for a target project.
 *
 * Calls the agentbootup server's /v1/brain-db/provision endpoint to get the
 * per-brain DB URL and auth token. If the server doesn't support this endpoint yet,
 * falls back to file-only mode (db.ts + schema written, no remote sync configured).
 *
 * Sync is handled by the `agentbootup-brain-db-<id>` daemon (agent-process),
 * started by `agentbootup daemon start`. No session hooks are written.
 *
 * @param {{
 *   brainId: string,
 *   target: string,
 *   apiKey: string,
 *   serverUrl: string,
 *   force: boolean,
 *   dryRun: boolean,
 *   verbose: boolean,
 * }} opts
 * @returns {Promise<{
 *   mode: 'embedded-replica' | 'file-only',
 *   message: string,
 * }>}
 */
export async function provisionBrainDb(opts) {
  const { brainId, target, apiKey, serverUrl, force, dryRun, verbose } = opts;

  let dbUrl = null;
  let dbToken = null;

  // ── Step 1: Request DB URL + JWT from agentbootup server ──────────────────
  // Skip the server call in dry-run — provision creates a JWT credential and
  // has a side effect (server may record the provision). Dry-run must be
  // read-only; show a preview message instead.
  if (dryRun) {
    if (verbose) console.log('  [dry-run] would call POST /v1/brain-db/provision — skipping server call');
    return { mode: 'file-only', message: 'brain.db provisioning skipped (dry-run)' };
  }

  try {
    const resp = await fetch(apiUrl(serverUrl, '/v1/brain-db/provision'), {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ brain_id: brainId }),
      signal: AbortSignal.timeout(PROVISION_TIMEOUT_MS),
    });

    if (resp.ok) {
      const body = await resp.json();
      dbUrl = body?.data?.db_url ?? null;
      dbToken = body?.data?.db_token ?? null;
    } else if (resp.status === 404) {
      if (verbose) console.log('  [brain-db] Server does not support brain-db provisioning yet — file-only mode.');
    } else {
      const msg = await resp.text().catch(() => `HTTP ${resp.status}`);
      if (verbose) console.log(`  [brain-db] Provision request failed (${resp.status}): ${msg} — file-only mode.`);
    }
  } catch (err) {
    if (verbose) console.log(`  [brain-db] Provision request error: ${err.message} — file-only mode.`);
  }

  const mode = dbUrl ? 'embedded-replica' : 'file-only';

  // ── Step 2: Install @libsql/client in target project ─────────────────────
  installLibsqlClient(target, { dryRun, verbose });

  // ── Step 3: Write .brain/db.ts ────────────────────────────────────────────
  writeFile(path.join(target, '.brain/db.ts'), DB_TS_TEMPLATE, { force, dryRun, verbose }); // nosemgrep

  // ── Step 4: Copy brain-schema.sql (FR-07 committed + runtime mirror) ─────
  const schema = readSchema();
  if (schema) {
    writeFile(path.join(target, BRAIN_SCHEMA_REL_COMMITTED), schema, { force, dryRun, verbose }); // nosemgrep
    writeFile(path.join(target, BRAIN_SCHEMA_REL_RUNTIME), schema, { force, dryRun, verbose }); // nosemgrep
  } else {
    if (verbose) console.log('  [brain-db] brain-schema.sql not found — skipping. Run `agentbootup brain restore --force` after templates/brain/brain-schema.sql is bundled.');
  }

  // ── Step 5: Append BRAIN_DB_URL + BRAIN_DB_TOKEN to .env ─────────────────
  if (dbUrl && dbToken) {
    appendEnvVars(
      path.join(target, '.env'), // nosemgrep
      { BRAIN_DB_URL: dbUrl, BRAIN_DB_TOKEN: dbToken },
      { dryRun, verbose, force },
    );
  }

  // ── Step 6: Allocate inbox port + generate webhook secret (AB-1, AB-2) ──────
  let inboxPort = null;
  let inboxSecret = null;
  if (!dryRun) {
    try {
      inboxPort = await allocateInboxPort(brainId);
      // Don't attempt mech-plane registration at provision time — the mech-plane
      // URL is distinct from the agentbootup server URL and is not available here.
      // Registration happens in getInboxAgentEntries() during `daemon start`.
      const webhookResult = await provisionWebhookSecret(brainId, inboxPort, {
        mechPlaneUrl: null,
        verbose,
      });
      inboxSecret = webhookResult.secret;
    } catch (err) {
      // Non-fatal — inbox daemon can be provisioned later.
      if (verbose) console.log(`  [brain-db] inbox provisioning error (non-fatal): ${err.message}`);
    }
    // Set the opt-in flag separately — a flag write failure must not be
    // confused with a provisioning failure (port + secret may already be set).
    if (inboxPort !== null && inboxSecret !== null) {
      try {
        await setInboxEnabled(brainId, true);
      } catch (err) {
        if (verbose) console.log(`  [brain-db] inbox flag write error (non-fatal): ${err.message}`);
      }
    }
  } else if (verbose) {
    console.log('  [dry-run] would allocate inbox port (8767–8867) and generate HMAC webhook secret');
  }

  // ── Step 7: Append inbox env vars to .env (AB-4) ─────────────────────────
  if (inboxPort !== null && inboxSecret !== null) {
    appendEnvVars(
      path.join(target, '.env'), // nosemgrep
      {
        AGENTBOOTUP_INBOX_PORT: String(inboxPort),
        AGENTBOOTUP_INBOX_WEBHOOK_SECRET: inboxSecret,
      },
      { dryRun, verbose, force },
    );
  }

  // ── Step 8: Add .brain/brain.db to .gitignore ─────────────────────────────
  appendGitignoreEntry(
    path.join(target, '.gitignore'), // nosemgrep
    '.brain/brain.db',
    { dryRun, verbose },
  );

  const modeLabel = mode === 'embedded-replica'
    ? 'embedded-replica (run `agentbootup daemon start` to activate sync)'
    : 'file-only (no remote sync — run restore again after server is configured)';
  return { mode, message: `brain.db provisioned — ${modeLabel}` };
}

/**
 * Provision brain.db in LOCAL-FIRST boot mode — no server call.
 *
 * Called by `agentbootup brain restore --boot`. Writes the same local files as
 * {@link provisionBrainDb} (db.ts, brain-schema.sql, .gitignore) but skips the
 * `/v1/brain-db/provision` network call and inbox port allocation. The generated
 * db.ts reads BRAIN_DB_URL / BRAIN_DB_TOKEN from the process environment at
 * runtime; sync is automatically configured when those env vars are present.
 * Sync is never required for the boot to succeed.
 *
 * @param {{
 *   brainId: string,
 *   target: string,
 *   verbose?: boolean,
 * }} opts
 * @returns {{ mode: 'file-only', message: string }}
 */
export async function provisionBrainDbBoot({ brainId: _brainId, target, verbose = false }) {
  // Boot containers are pre-baked — @libsql/client must already be installed before
  // boot runs. We skip the install step (installLibsqlClient) because execFileSync
  // hangs indefinitely when the package registry is unreachable inside a locked
  // container, defeating fail-closed boot. The generated .brain/db.ts hard-imports
  // @libsql/client, so the package MUST be present in target/node_modules; if it
  // is not, we fail with a clear error rather than emitting a broken runtime.
  const libsqlClientDir = path.join(target, 'node_modules', '@libsql', 'client');
  if (!fs.existsSync(libsqlClientDir)) {
    throw new Error(
      '[brain-db] boot mode requires @libsql/client to be pre-installed in the target ' +
      `(${target}/node_modules/@libsql/client not found). Install it before running boot.`,
    );
  }

  if (verbose) {
    console.log('  [brain-db] boot mode: @libsql/client verified (pre-baked container)');
  }

  // Write .brain/db.ts — the template reads BRAIN_DB_URL/BRAIN_DB_TOKEN from env
  // at runtime, so sync is automatically configured when those env vars are present.
  writeFile(path.join(target, '.brain/db.ts'), DB_TS_TEMPLATE, { force: false, dryRun: false, verbose }); // nosemgrep

  // Copy brain-schema.sql to both committed and runtime locations.
  const schema = readSchema();
  if (schema) {
    writeFile(path.join(target, BRAIN_SCHEMA_REL_COMMITTED), schema, { force: false, dryRun: false, verbose }); // nosemgrep
    writeFile(path.join(target, BRAIN_SCHEMA_REL_RUNTIME), schema, { force: false, dryRun: false, verbose }); // nosemgrep
  } else if (verbose) {
    console.log('  [brain-db] brain-schema.sql not found — skipping schema install.');
  }

  // Add .brain/brain.db to .gitignore (idempotent).
  appendGitignoreEntry(
    path.join(target, '.gitignore'), // nosemgrep
    '.brain/brain.db',
    { dryRun: false, verbose },
  );

  return {
    mode: 'file-only',
    message: 'brain.db provisioned (local-first boot; sync configured from env vars at runtime)',
  };
}
